### ISSUE TITLE
error when running training when nerblackbox installed in virtualenv

### ISSUE THREAD

**Issue by gromajus** [flxst/nerblackbox#13] opened 2023-08-23 08:04 UTC
### System Info

nerblackbox: v1.0.0
python 3.8
ubuntu20.04: docker image: nvidia/cuda:12.1.1-runtime-ubuntu20.04
virtualenv

### 🐛 Describe the bug

Hi!
I have installed nerblackbox inside virtualenv.
I can set up dataset, create training but when I run training I get the following error:

```
2023/08/22 15:44:10 INFO mlflow.projects: 'expe_0' does not exist. Creating a new experiment
2023/08/22 15:44:11 INFO mlflow.projects.utils: === Created directory /tmp/tmphy500ub5 for downloading remote URIs passed to arguments of type 'path' ===
2023/08/22 15:44:11 INFO mlflow.projects.backend.local: === Running command 'python modules/scripts/script_run_training.py \
--training_name bner_2022_expe_3 \
--from_config 0 \
--run_name '' \
--device gpu \
--fp16 0
' in run with ID 'b165910e80c54097a16d421298f8e05e' === 
Traceback (most recent call last):
  File "modules/scripts/script_run_training.py", line 2, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
---------------------------------------------------------------------------
ExecutionException                        Traceback (most recent call last)
Cell In[16], line 1
----> 1 experiment.run()

File /business_entities_with_dvc/env_active_learning/lib/python3.8/site-packages/nerblackbox/api/training.py:135, in Training.run(self)
    132     assert self.hparams is not None, f"ERROR! self.hparams is None."
    133     self._write_config_file(hparams=self.hparams)
--> 135 mlflow.projects.run(
    136     uri=resource_filename(Requirement.parse("nerblackbox"), "nerblackbox"),
    137     entry_point="run_training",
    138     experiment_name=self.training_name,
    139     parameters=_parameters,
    140     env_manager="local",
    141 )
    143 training_exists, self.results = Store.get_training_results_single(
    144     self.training_name,
    145     verbose=self.verbose,
    146 )
    147 assert (
    148     training_exists
    149 ), f"ERROR! training = {self.training_name} does not exist."

File /ner/env_active_learning/lib/python3.8/site-packages/mlflow/projects/__init__.py:354, in run(uri, entry_point, version, parameters, docker_args, experiment_name, experiment_id, backend, backend_config, storage_dir, synchronous, run_id, run_name, env_manager, build_image, docker_auth)
    337 submitted_run_obj = _run(
    338     uri=uri,
    339     experiment_id=experiment_id,
   (...)
    351     docker_auth=docker_auth,
    352 )
    353 if synchronous:
--> 354     _wait_for(submitted_run_obj)
    355 return submitted_run_obj

File /nerc/env_active_learning/lib/python3.8/site-packages/mlflow/projects/__init__.py:371, in _wait_for(submitted_run_obj)
    369     else:
    370         _maybe_set_run_terminated(active_run, "FAILED")
--> 371         raise ExecutionException(f"Run (ID '{run_id}') failed")
    372 except KeyboardInterrupt:
    373     _logger.error("=== Run (ID '%s') interrupted, cancelling run ===", run_id)

ExecutionException: Run (ID 'b165910e80c54097a16d421298f8e05e') failed
```

Torch is actually installed in virtualenv, together with all nerblackbox dependencies.
I can execute code that imports torch, nerblackbox imports it as well before the above error.

It seems that the mlflow experiment is run outside the virtualenv, where torch is not installed.
I thought the work around would be to install torch outside virtualenv, it helped indeed, but then I've got the error that no mlflow, I installed mlflow outside the virtualenv, but I caused in error that `ModuleNotFoundError: No module named 'nerblackbox'`. So it seems I need to install nerblackbox outside the virtualenv which is not what I wanted.

@flxst do you have an idea how to make it possible run nerblackbox in virtualenv?

Justyna.

**Comment by flxst** [comment] 2023-08-23 18:19
Hey again, thanks for reporting this issue. This is quite strange. I always run nerblackbox in a virtual environment and have never seen this before. Another odd thing I noticed in your output is that in line 1, the training is called `expe_0`, but in line 4, it is called `bner_2022_expe_3`. Could the latter be the name of a training that you have run before?

I'd like to ask you to share
1) the output of `pip list | grep -E 'nerblackbox|mlflow|torch'` in your virtual environment
2) the full code that leads to the output that you copied and pasted above

**Comment by gromajus** [comment] 2023-08-24 11:07
Concerning training names, it was actually everywhere bner_2022_expe_3. I was trying not to reveal project name so I have changed it in the logs to expe_0 but I didn't notice the name in other place. So concerning training names, I was consistent.

So, I have repeated the whole experiment:
I have docker container based on nvidia/cuda:12.1.1-runtime-ubuntu20.04.
Then I run:
```
apt-get update
apt-get install git
apt-get install python3-pip
apt-get install python3.8-venv
apt-get install python-is-python3

python3 -m venv env_active_learning
source env_active_learning/bin/activate
pip3 install --upgrade pip
pip3 install nerblackbox
```

The output of `pip list | grep -E 'nerblackbox|mlflow|torch'`:
```
mlflow                    2.6.0
nerblackbox               1.0.0
pytorch-lightning         1.9.5
torch                     2.0.1
torchmetrics              0.11.4
```

In my virtual environment I run:
ipython kernel install --name=env_active_learning

jupyter is installed outside the virtual environment.

Then I downloaded your exemplary notebook: https://github.com/flxst/nerblackbox/blob/master/notebooks/huggingface.ipynb

I have only added:
```
import os
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
```
to the notebook, then run it untill `training.run()`
When I run this cell, I get: 
```
2023/08/24 11:05:56 INFO mlflow.projects: 'huggingface' does not exist. Creating a new experiment
2023/08/24 11:05:56 INFO mlflow.projects.utils: === Created directory /tmp/tmpg1pelwxe for downloading remote URIs passed to arguments of type 'path' ===
2023/08/24 11:05:56 INFO mlflow.projects.backend.local: === Running command 'python modules/scripts/script_run_training.py \
--training_name huggingface \
--from_config 0 \
--run_name '' \
--device gpu \
--fp16 0
' in run with ID 'e83f954bb5734924a130338445a81cab' === 
Traceback (most recent call last):
  File "modules/scripts/script_run_training.py", line 2, in <module>
    import torch
ModuleNotFoundError: No module named 'torch'
---------------------------------------------------------------------------
ExecutionException                        Traceback (most recent call last)
Cell In[8], line 2
      1 # run the training (this will take at least a few minutes)
----> 2 training.run()

File /env_active_learning/lib/python3.8/site-packages/nerblackbox/api/training.py:135, in Training.run(self)
    132     assert self.hparams is not None, f"ERROR! self.hparams is None."
    133     self._write_config_file(hparams=self.hparams)
--> 135 mlflow.projects.run(
    136     uri=resource_filename(Requirement.parse("nerblackbox"), "nerblackbox"),
    137     entry_point="run_training",
    138     experiment_name=self.training_name,
    139     parameters=_parameters,
    140     env_manager="local",
    141 )
    143 training_exists, self.results = Store.get_training_results_single(
    144     self.training_name,
    145     verbose=self.verbose,
    146 )
    147 assert (
    148     training_exists
    149 ), f"ERROR! training = {self.training_name} does not exist."

File /env_active_learning/lib/python3.8/site-packages/mlflow/projects/__init__.py:354, in run(uri, entry_point, version, parameters, docker_args, experiment_name, experiment_id, backend, backend_config, storage_dir, synchronous, run_id, run_name, env_manager, build_image, docker_auth)
    337 submitted_run_obj = _run(
    338     uri=uri,
    339     experiment_id=experiment_id,
   (...)
    351     docker_auth=docker_auth,
    352 )
    353 if synchronous:
--> 354     _wait_for(submitted_run_obj)
    355 return submitted_run_obj

File /env_active_learning/lib/python3.8/site-packages/mlflow/projects/__init__.py:371, in _wait_for(submitted_run_obj)
    369     else:
    370         _maybe_set_run_terminated(active_run, "FAILED")
--> 371         raise ExecutionException(f"Run (ID '{run_id}') failed")
    372 except KeyboardInterrupt:
    373     _logger.error("=== Run (ID '%s') interrupted, cancelling run ===", run_id)

ExecutionException: Run (ID 'e83f954bb5734924a130338445a81cab') failed
```

Justyna

**Comment by flxst** [comment] 2023-08-28 08:28
Hey Justyna, thanks for the detailed description. I don’t think this is an issue with nerblackbox, but rather a general problem with the interplay of Docker, Jupyter and venv. 

I could not reproduce your error, but instead managed to get the notebook working in a docker container with a slightly modified approach. 

On host (System: macOS 12.6, Docker Desktop 4.11.1): 
```
docker pull nvidia/cuda:12.1.1-runtime-ubuntu20.04
docker run -p 8888:8888 -it dc178d8bf3f3 sh
```
In docker container:
```
# set up python, pip, venv, curl
apt-get update
apt-get install git -y
apt-get install python3-pip -y
apt-get install python3.8-venv -y
apt-get install python-is-python3
apt-get install curl -y

# install rust (apparently needed in order for safetensors to work)
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh    # -> choose option 1
PATH="/root/.cargo/bin:${PATH}"

# activate and set up virtual environment
python -m venv env_active_learning
. env_active_learning/bin/activate
pip install --upgrade pip
pip install nerblackbox

# set up and run notebook 
mkdir nerblackbox; cd nerblackbox
curl https://raw.githubusercontent.com/flxst/nerblackbox/master/notebooks/huggingface.ipynb --output huggingface.ipynb
jupyter notebook --allow-root --ip 0.0.0.0 --no-browser
```
The virtual environment is automatically activated in the notebook and the training works fine. Hope this helps you somehow.
I am going to close the issue since I think this is neither a bug nor directly related to nerblackbox, but feel free to continue the discussion!

**Closed by flxst** 2023-08-28 08:28 UTC
Labels: bug
